# Generated by Django 3.1.2 on 2020-11-13 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('birth_date', models.DateField(blank=True)),
                ('pesel', models.CharField(blank=True, max_length=11)),
                ('id_number', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('street', models.CharField(blank=True, max_length=30)),
                ('street_number', models.CharField(blank=True, max_length=5)),
                ('postal_code', models.CharField(blank=True, max_length=6)),
                ('is_client', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('birth_date', models.DateField(blank=True)),
                ('pesel', models.CharField(blank=True, max_length=11)),
                ('id_number', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('street', models.CharField(blank=True, max_length=30)),
                ('street_number', models.CharField(blank=True, max_length=5)),
                ('postal_code', models.CharField(blank=True, max_length=6)),
                ('is_employee', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Headadmin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('birth_date', models.DateField(blank=True)),
                ('pesel', models.CharField(blank=True, max_length=11)),
                ('id_number', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('street', models.CharField(blank=True, max_length=30)),
                ('street_number', models.CharField(blank=True, max_length=5)),
                ('postal_code', models.CharField(blank=True, max_length=6)),
            ],
        ),
    ]
