# Generated by Django 3.1.2 on 2020-11-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/profilepics/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/profilepics/'),
        ),
        migrations.AddField(
            model_name='headadmin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/profilepics/'),
        ),
    ]
