# Generated by Django 3.1.2 on 2020-11-13 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201113_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='headadmin',
            name='photo',
        ),
    ]
