# Generated by Django 3.1.2 on 2020-11-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('generation', models.CharField(blank=True, max_length=10, null=True)),
                ('year_of_production', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=40)),
                ('engine', models.CharField(max_length=10)),
                ('hourse_power', models.CharField(max_length=10)),
                ('body_type', models.CharField(max_length=40)),
                ('seats', models.IntegerField(default=5)),
                ('doors', models.IntegerField(default=5)),
                ('acceleration', models.CharField(max_length=10)),
                ('max_speed', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='carimages/')),
                ('to_rent', models.BooleanField(default=False)),
                ('other_info', models.TextField(blank=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'ordering': ('brand',),
            },
        ),
    ]
