# Generated by Django 3.1.2 on 2020-11-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='hourse_power',
        ),
    ]
