# Generated by Django 3.1.2 on 2020-11-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_hourse_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='hourse_power',
            field=models.CharField(default='0 hp', max_length=10),
        ),
    ]
